-- Inserir promoções de exemplo encontradas pelo bot

INSERT INTO promotions (
  title,
  description,
  price,
  old_price,
  discount_percent,
  url,
  store,
  category,
  source_telegram_group,
  status,
  created_at,
  updated_at
) VALUES
(
  'JBL Boombox 4 Bluetooth Amplified Portable 210W',
  'JBL Boombox 4 Bluetooth Amplified Portable 210W USB e P2 Preto',
  2331.00,
  3500.00,
  33,
  'https://s.click.aliexpress.com/e/_DmFcIvv',
  'Aliexpress',
  'Eletrônicos',
  'economizanderson',
  'active',
  NOW(),
  NOW()
),
(
  'Kit Com 2 Camisetas Masculina Crew-neck Calvin Klein',
  'Kit Com 2 Camisetas Masculina Crew-neck Calvin Klein Original',
  40.00,
  120.00,
  67,
  'https://mercadolivre.com.br',
  'Mercado Livre',
  'Moda',
  'economizanderson',
  'active',
  NOW(),
  NOW()
),
(
  'Notebook Gamer Lenovo LOQ E Core i5-12450HX 8GB 512GB',
  'Notebook Gamer Lenovo LOQ E Core i5-12450HX 8GB 512GB SSD RTX 3050 15.6" FHD',
  3420.00,
  4500.00,
  24,
  'https://amazon.com.br',
  'Amazon',
  'Eletrônicos',
  'descontoemgames',
  'active',
  NOW(),
  NOW()
),
(
  'Controle PowerA Nano com Fio + Grip Pokémon',
  'Controle PowerA Nano com Fio + Grip Pokémon Sweet Dreams para Nintendo Switch',
  145.64,
  200.00,
  27,
  'https://amazon.com.br',
  'Amazon',
  'Games',
  'descontoemgames',
  'active',
  NOW(),
  NOW()
),
(
  'Suporte Apoio De Notebook Laptop Compacto',
  'Suporte Apoio De Notebook Laptop Compacto Articulado Ergonômico',
  10.00,
  30.00,
  67,
  'https://shopee.com.br',
  'Shopee',
  'Eletrônicos',
  'especialistaemti',
  'active',
  NOW(),
  NOW()
),
(
  'Celular Samsung Galaxy A56 5G, 8GB, 128GB',
  'Celular Samsung Galaxy A56 5G, 8GB, 128GB, Tela 6.5"',
  1609.00,
  2200.00,
  27,
  'https://aliexpress.com',
  'Aliexpress',
  'Eletrônicos',
  'especialistaemti',
  'active',
  NOW(),
  NOW()
),
(
  'Echo Dot 5ª geração Amazon, com Alexa',
  'Echo Dot 5ª geração Amazon, com Alexa, Smart Speaker',
  255.00,
  350.00,
  27,
  'https://amazon.com.br',
  'Amazon',
  'Eletrônicos',
  'infoBRpromos',
  'active',
  NOW(),
  NOW()
),
(
  'Placa de Vídeo MSI NVIDIA GeForce RTX 5060',
  'Placa de Vídeo MSI NVIDIA GeForce RTX 5060 Inspire 8GB GDDR6',
  1999.00,
  2800.00,
  29,
  'https://kabum.com.br',
  'Kabum',
  'Eletrônicos',
  'infoBRpromos',
  'active',
  NOW(),
  NOW()
),
(
  'Water Cooler DeepCool LE240 V2, ARGB, 240mm',
  'Water Cooler DeepCool LE240 V2, ARGB, 240mm, Intel e AMD',
  269.00,
  400.00,
  33,
  'https://kabum.com.br',
  'Kabum',
  'Eletrônicos',
  'infoBRpromos',
  'active',
  NOW(),
  NOW()
),
(
  'Notebook Acer Aspire Go 15 AG15-71P-76Z8 Intel i7',
  'Notebook Acer Aspire Go 15 AG15-71P-76Z8 Intel i7 8GB 512GB SSD',
  2860.00,
  3800.00,
  25,
  'https://amazon.com.br',
  'Amazon',
  'Eletrônicos',
  'especialistaemti',
  'active',
  NOW(),
  NOW()
),
(
  'Celular Samsung Galaxy S24, 8GB, 256GB',
  'Celular Samsung Galaxy S24, 8GB, 256GB, Tela de 6.2"',
  2799.00,
  3800.00,
  26,
  'https://aliexpress.com',
  'Aliexpress',
  'Eletrônicos',
  'especialistaemti',
  'active',
  NOW(),
  NOW()
),
(
  'Webcam Full HD Logitech C920s com Microfone',
  'Webcam Full HD Logitech C920s com Microfone Embutido 1080p',
  340.00,
  500.00,
  32,
  'https://amazon.com.br',
  'Amazon',
  'Eletrônicos',
  'especialistaemti',
  'active',
  NOW(),
  NOW()
);
